{"cells":[{"cell_type":"code","source":["from google.colab import drive\n","drive.mount('/content/drive')"],"metadata":{"id":"fk0qHEJXM0Wx","executionInfo":{"status":"ok","timestamp":1717085377322,"user_tz":180,"elapsed":3387,"user":{"displayName":"","userId":""}},"outputId":"3583deaf-26de-4b83-f902-53dc7552c5d9","colab":{"base_uri":"https://localhost:8080/"}},"id":"fk0qHEJXM0Wx","execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"]}]},{"cell_type":"code","source":["# Run this to setup the files and requirements\n","\n","%cd /content\n","#%rm -rf qr\n","\n","!git clone https://github.com/linobigatti/quadrantrecon qr\n","%cd qr\n","!git submodule update --init --recursive\n","\n","!pip install -r ./requirements.txt\n","!pip install -r ./requirements-torch.txt\n","\n","!wget -nc https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth\n","!ln -s sam_vit_h_4b8939.pth sam_vit_h.pth"],"metadata":{"id":"qiddTUVgMcld","executionInfo":{"status":"ok","timestamp":1717087955159,"user_tz":180,"elapsed":8931,"user":{"displayName":"","userId":""}},"outputId":"5da84949-5424-4aca-962c-d41514373d39","colab":{"base_uri":"https://localhost:8080/"}},"id":"qiddTUVgMcld","execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["/content\n","fatal: destination path 'qr' already exists and is not an empty directory.\n","/content/qr\n","Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 1)) (23.2.0)\n","Requirement already satisfied: autocommand>=2.2.2 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 2)) (2.2.2)\n","Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 3)) (1.16.0)\n","Requirement already satisfied: charset-normalizer>=3.3.2 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 4)) (3.3.2)\n","Requirement already satisfied: contourpy>=1.2.1 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 5)) (1.2.1)\n","Requirement already satisfied: cryptography>=42.0.5 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 6)) (42.0.7)\n","Requirement already satisfied: cycler>=0.12.1 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 7)) (0.12.1)\n","Requirement already satisfied: fastjsonschema>=2.19.1 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 8)) (2.19.1)\n","Requirement already satisfied: filelock>=3.14.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 9)) (3.14.0)\n","Requirement already satisfied: fonttools>=4.51.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 10)) (4.51.0)\n","Requirement already satisfied: fsspec>=2024.3.1 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 11)) (2024.5.0)\n","Requirement already satisfied: future>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 12)) (1.0.0)\n","Requirement already satisfied: gmpy2>=2.2.0a1 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 13)) (2.2.0a1)\n","Requirement already satisfied: idna>=3.6 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 14)) (3.7)\n","Requirement already satisfied: inflect>=7.2.1 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 15)) (7.2.1)\n","Requirement already satisfied: jaraco.context>=4.3.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 16)) (5.3.0)\n","Requirement already satisfied: jaraco.functools>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 17)) (4.0.1)\n","Requirement already satisfied: jaraco.text>=3.12.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 18)) (3.12.0)\n","Requirement already satisfied: Jinja2>=3.1.3 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 19)) (3.1.4)\n","Requirement already satisfied: kiwisolver>=1.4.5 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 20)) (1.4.5)\n","Requirement already satisfied: MarkupSafe>=2.1.5 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 21)) (2.1.5)\n","Requirement already satisfied: matplotlib>=3.8.4 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 22)) (3.9.0)\n","Requirement already satisfied: more-itertools>=10.2.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 23)) (10.2.0)\n","Requirement already satisfied: mpmath>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 24)) (1.3.0)\n","Requirement already satisfied: networkx>=3.3 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 25)) (3.3)\n","Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 26)) (1.26.4)\n","Requirement already satisfied: opencv-python>=4.9.0.80 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 27)) (4.9.0.80)\n","Requirement already satisfied: ordered-set>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 28)) (4.1.0)\n","Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 29)) (24.0)\n","Requirement already satisfied: pandas>=1.5.3 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 30)) (2.0.3)\n","Requirement already satisfied: pillow>=10.3.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 31)) (10.3.0)\n","Requirement already satisfied: platformdirs>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 32)) (4.2.2)\n","Requirement already satisfied: pooch>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 33)) (1.8.1)\n","Requirement already satisfied: pybind11>=2.12.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 34)) (2.12.0)\n","Requirement already satisfied: pycparser>=2.22 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 35)) (2.22)\n","Requirement already satisfied: pyparsing>=3.1.2 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 36)) (3.1.2)\n","Requirement already satisfied: python-dateutil>=2.9.0.post0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 37)) (2.9.0.post0)\n","Requirement already satisfied: pytz>=2024.1 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 38)) (2024.1)\n","Requirement already satisfied: PyYAML>=6.0.1 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 39)) (6.0.1)\n","Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 40)) (2.31.0)\n","Requirement already satisfied: scipy>=1.13.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 41)) (1.13.1)\n","Requirement already satisfied: setuptools>=69.0.3 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 42)) (70.0.0)\n","Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 43)) (1.16.0)\n","Requirement already satisfied: smbus>=1.1 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 44)) (1.1.post2)\n","Requirement already satisfied: sympy>=1.12 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 45)) (1.12)\n","Requirement already satisfied: TBB>=0.2 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 46)) (2021.12.0)\n","Requirement already satisfied: tomli>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 47)) (2.0.1)\n","Requirement already satisfied: trove-classifiers>=2024.4.10 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 48)) (2024.5.22)\n","Requirement already satisfied: typeguard>=4.2.1 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 49)) (4.3.0)\n","Requirement already satisfied: typing_extensions>=4.11.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 50)) (4.11.0)\n","Requirement already satisfied: urllib3>=1.26.18 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 51)) (2.0.7)\n","Requirement already satisfied: validate-pyproject>=0.16 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 52)) (0.18)\n","Requirement already satisfied: wheel>=0.43.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 53)) (0.43.0)\n","Requirement already satisfied: tk>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 54)) (0.1.0)\n","Requirement already satisfied: pyinstaller>=6.6.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 55)) (6.7.0)\n","Requirement already satisfied: piexif>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements.txt (line 56)) (1.1.3)\n","Requirement already satisfied: backports.tarfile in /usr/local/lib/python3.10/dist-packages (from jaraco.context>=4.3.0->-r ./requirements.txt (line 16)) (1.2.0)\n","Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5.3->-r ./requirements.txt (line 30)) (2024.1)\n","Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31.0->-r ./requirements.txt (line 40)) (2024.2.2)\n","Requirement already satisfied: altgraph in /usr/local/lib/python3.10/dist-packages (from pyinstaller>=6.6.0->-r ./requirements.txt (line 55)) (0.17.4)\n","Requirement already satisfied: pyinstaller-hooks-contrib>=2024.6 in /usr/local/lib/python3.10/dist-packages (from pyinstaller>=6.6.0->-r ./requirements.txt (line 55)) (2024.6)\n","\u001b[31mERROR: Operation cancelled by user\u001b[0m\u001b[31m\n","\u001b[0mTraceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 3108, in _dep_map\n","    return self.__dep_map\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 2901, in __getattr__\n","    raise AttributeError(attr)\n","AttributeError: _DistInfoDistribution__dep_map\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 169, in exc_logging_wrapper\n","    status = run_func(*args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py\", line 242, in wrapper\n","    return func(self, options, args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py\", line 441, in run\n","    conflicts = self._determine_conflicts(to_install)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py\", line 572, in _determine_conflicts\n","    return check_install_conflicts(to_install)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/check.py\", line 101, in check_install_conflicts\n","    package_set, _ = create_package_set_from_installed()\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/check.py\", line 42, in create_package_set_from_installed\n","    dependencies = list(dist.iter_dependencies())\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/metadata/pkg_resources.py\", line 216, in iter_dependencies\n","    return self._dist.requires(extras)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 2821, in requires\n","    dm = self._dep_map\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 3110, in _dep_map\n","    self.__dep_map = self._compute_dependencies()\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 3120, in _compute_dependencies\n","    reqs.extend(parse_requirements(req))\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 3173, in __init__\n","    super(Requirement, self).__init__(requirement_string)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/packaging/requirements.py\", line 102, in __init__\n","    req = REQUIREMENT.parseString(requirement_string)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 1131, in parse_string\n","    loc, tokens = self._parse(instring, 0)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 817, in _parseNoCache\n","    loc, tokens = self.parseImpl(instring, pre_loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 3886, in parseImpl\n","    loc, exprtokens = e._parse(instring, loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 817, in _parseNoCache\n","    loc, tokens = self.parseImpl(instring, pre_loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 4114, in parseImpl\n","    return e._parse(\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 817, in _parseNoCache\n","    loc, tokens = self.parseImpl(instring, pre_loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 3886, in parseImpl\n","    loc, exprtokens = e._parse(instring, loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 817, in _parseNoCache\n","    loc, tokens = self.parseImpl(instring, pre_loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 4959, in parseImpl\n","    loc, tokens = self_expr._parse(instring, loc, doActions, callPreParse=False)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 817, in _parseNoCache\n","    loc, tokens = self.parseImpl(instring, pre_loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 3886, in parseImpl\n","    loc, exprtokens = e._parse(instring, loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 817, in _parseNoCache\n","    loc, tokens = self.parseImpl(instring, pre_loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 3886, in parseImpl\n","    loc, exprtokens = e._parse(instring, loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 817, in _parseNoCache\n","    loc, tokens = self.parseImpl(instring, pre_loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 5226, in parseImpl\n","    return super().parseImpl(instring, loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 4375, in parseImpl\n","    return self.expr._parse(instring, loc, doActions, callPreParse=False)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 817, in _parseNoCache\n","    loc, tokens = self.parseImpl(instring, pre_loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 3864, in parseImpl\n","    loc, resultlist = self.exprs[0]._parse(\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 817, in _parseNoCache\n","    loc, tokens = self.parseImpl(instring, pre_loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 4114, in parseImpl\n","    return e._parse(\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 817, in _parseNoCache\n","    loc, tokens = self.parseImpl(instring, pre_loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 4375, in parseImpl\n","    return self.expr._parse(instring, loc, doActions, callPreParse=False)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 817, in _parseNoCache\n","    loc, tokens = self.parseImpl(instring, pre_loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 3864, in parseImpl\n","    loc, resultlist = self.exprs[0]._parse(\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 817, in _parseNoCache\n","    loc, tokens = self.parseImpl(instring, pre_loc, doActions)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py\", line 4108, in parseImpl\n","    def parseImpl(self, instring, loc, doActions=True):\n","KeyboardInterrupt\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/bin/pip3\", line 8, in <module>\n","    sys.exit(main())\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/main.py\", line 79, in main\n","    return command.main(cmd_args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 101, in main\n","    return self._main(args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 223, in _main\n","    return run(options, args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 207, in exc_logging_wrapper\n","    logger.debug(\"Exception information:\", exc_info=True)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 1465, in debug\n","    self._log(DEBUG, msg, args, **kwargs)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 1624, in _log\n","    self.handle(record)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 1634, in handle\n","    self.callHandlers(record)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 1696, in callHandlers\n","    hdlr.handle(record)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 968, in handle\n","    self.emit(record)\n","  File \"/usr/lib/python3.10/logging/handlers.py\", line 75, in emit\n","    logging.FileHandler.emit(self, record)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 1218, in emit\n","    StreamHandler.emit(self, record)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 1100, in emit\n","    msg = self.format(record)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 943, in format\n","    return fmt.format(record)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/logging.py\", line 112, in format\n","    formatted = super().format(record)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 686, in format\n","    record.exc_text = self.formatException(record.exc_info)\n","  File \"/usr/lib/python3.10/logging/__init__.py\", line 636, in formatException\n","    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n","  File \"/usr/lib/python3.10/traceback.py\", line 119, in print_exception\n","    te = TracebackException(type(value), value, tb, limit=limit, compact=True)\n","  File \"/usr/lib/python3.10/traceback.py\", line 502, in __init__\n","    self.stack = StackSummary.extract(\n","  File \"/usr/lib/python3.10/traceback.py\", line 383, in extract\n","    f.line\n","  File \"/usr/lib/python3.10/traceback.py\", line 306, in line\n","    self._line = linecache.getline(self.filename, self.lineno)\n","  File \"/usr/lib/python3.10/linecache.py\", line 30, in getline\n","    lines = getlines(filename, module_globals)\n","  File \"/usr/lib/python3.10/linecache.py\", line 46, in getlines\n","    return updatecache(filename, module_globals)\n","  File \"/usr/lib/python3.10/linecache.py\", line 136, in updatecache\n","    with tokenize.open(fullname) as fp:\n","  File \"/usr/lib/python3.10/tokenize.py\", line 396, in open\n","    encoding, lines = detect_encoding(buffer.readline)\n","  File \"/usr/lib/python3.10/tokenize.py\", line 365, in detect_encoding\n","    first = read_or_stop()\n","  File \"/usr/lib/python3.10/tokenize.py\", line 323, in read_or_stop\n","    return readline()\n","KeyboardInterrupt\n","^C\n","Requirement already satisfied: torch>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements-torch.txt (line 1)) (2.3.0+cu121)\n","Requirement already satisfied: torchvision>=0.18.0 in /usr/local/lib/python3.10/dist-packages (from -r ./requirements-torch.txt (line 2)) (0.18.0+cu121)\n","Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (3.14.0)\n","Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (4.11.0)\n","Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (1.12)\n","Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (3.3)\n","Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (3.1.4)\n","Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (2024.5.0)\n","Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (12.1.105)\n","Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (12.1.105)\n","Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (12.1.105)\n","Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (8.9.2.26)\n","Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (12.1.3.1)\n","Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (11.0.2.54)\n","Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (10.3.2.106)\n","Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (11.4.5.107)\n","Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (12.1.0.106)\n","Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (2.20.5)\n","Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (12.1.105)\n","Requirement already satisfied: triton==2.3.0 in /usr/local/lib/python3.10/dist-packages (from torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (2.3.0)\n","Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (12.5.40)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from torchvision>=0.18.0->-r ./requirements-torch.txt (line 2)) (1.26.4)\n","Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision>=0.18.0->-r ./requirements-torch.txt (line 2)) (10.3.0)\n","Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (2.1.5)\n","Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=2.3.0->-r ./requirements-torch.txt (line 1)) (1.3.0)\n","File ‘sam_vit_h_4b8939.pth’ already there; not retrieving.\n","\n","ln: failed to create symbolic link 'sam_vit_h.pth': File exists\n"]}]},{"cell_type":"code","execution_count":null,"id":"e9ac6cca-bc50-4a61-b4a5-3ff45540804c","metadata":{"id":"e9ac6cca-bc50-4a61-b4a5-3ff45540804c","executionInfo":{"status":"ok","timestamp":1717087828886,"user_tz":180,"elapsed":872,"user":{"displayName":"","userId":""}},"outputId":"d5cb378a-ebf5-4cd0-89be-75e5a1dcc858","colab":{"base_uri":"https://localhost:8080/"}},"outputs":[{"output_type":"execute_result","data":{"text/plain":["<main.QuadrantRecon at 0x7849a8977f10>"]},"metadata":{},"execution_count":6}],"source":["import main as quadrantrecon\n","\n","# Load default arguments\n","qr = quadrantrecon.QuadrantRecon()"]},{"cell_type":"code","execution_count":null,"id":"c87a4769-f02c-44b8-9ef6-fdc80146f4b2","metadata":{"id":"c87a4769-f02c-44b8-9ef6-fdc80146f4b2"},"outputs":[],"source":["# Set options (defaults are commented out)\n","qr.verbose = True\n","qr.plot = False\n","qr.dry_run = True\n","qr.device = \"cuda\"\n","#qr.model_path = \"sam_vit_h.pth\"\n","#qr.model_type = \"vit_h\"\n","#qr.width = 1790\n","#qr.height = 1790\n","\n","# Set files to process\n","files = [\n","    \"/content/AMP50082.JPG\",\n","]"]},{"cell_type":"code","execution_count":null,"id":"9b8c3a52-d657-4f07-bff3-023c7345254e","metadata":{"id":"9b8c3a52-d657-4f07-bff3-023c7345254e","executionInfo":{"status":"ok","timestamp":1717087893434,"user_tz":180,"elapsed":21242,"user":{"displayName":"","userId":""}},"outputId":"bdd10cd9-a7b3-4911-8d87-73dc57ed4561","colab":{"base_uri":"https://localhost:8080/"}},"outputs":[{"output_type":"stream","name":"stdout","text":["Loading model...\n","Model loaded.\n","Creating predictor...\n","Loading image from path /content/AMP50082.JPG...\n","Image loaded.\n","Setting predictor image...\n","Predictor loaded\n","Predicting...\n","[0.75975484 0.85059774 0.8683053 ]\n","Searching for inner bounding box...\n"]}],"source":["qr.create_predictor()\n","\n","for filename in files:\n","    mask = qr.process_image(filename)"]},{"cell_type":"code","execution_count":null,"id":"650f417b-cefa-4aab-b1c1-64a2a4ab9426","metadata":{"id":"650f417b-cefa-4aab-b1c1-64a2a4ab9426"},"outputs":[],"source":[]}],"metadata":{"kernelspec":{"display_name":"quadrantrecon","language":"python","name":"quadrantrecon"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.12.3"},"colab":{"provenance":[{"file_id":"https://github.com/LinoBigatti/quadrantrecon/blob/master/Notebook.ipynb","timestamp":1717087957655}],"gpuType":"T4"},"accelerator":"GPU"},"nbformat":4,"nbformat_minor":5}
